spring.application.name=user-service

server.port=8081

spring.cassandra.contact-points=${CASSAANDRA_HOST:apache-cassandra}
spring.cassandra.port=${CASSANDRA_PORT:9042}
spring.cassandra.local-datacenter=${CASSANDRA_DC:my-datacenter-1}
spring.cassandra.keyspace-name=${CASSANDRA_KEYSPACE:user_service}
spring.cassandra.username=${CASSANDRA_USER:cassandra}
spring.cassandra.password=${CASSANDRA_PASSWORD:cassandra}

spring.cassandra.schema-action=${CASSANDRA_SCHEMA_ACTION:create-if-not-exists}

spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s
spring.cassandra.request.timeout=5s
