spring.application.name=user-service

server.port=8081

spring.autoconfigure.exclude=\
  org.springframework.boot.cassandra.autoconfigure.CassandraAutoConfiguration,\
  org.springframework.boot.data.cassandra.autoconfigure.DataCassandraAutoConfiguration
